name: GitHub Actions for LaTex 
on: [push]
jobs:
  Build-LaTex-Container:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Build Docker image
        run: docker build . --file Dockerfile --tag michaellihs/latex:latest
  Build-LaTex:
    runs-on: ubuntu-latest
    container: michaellihs/latex:latest
    steps:
      - name: Checkout Project
        uses: actions/checkout@v1